name: Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # For git push
    environment:
      name: pypi
      url: https://pypi.org/p/konokenj.cdk-api-mcp-server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Download CDK API
        run: hatch run dev:download

      - name: Run tests
        run: hatch test

      - name: Bump version
        run: hatch version minor

      - name: Build package
        run: hatch build

      - name: Get package version
        id: get_version
        run: echo "version=$(python -c "from cdk_api_mcp_server.__about__ import __version__; print(__version__)")" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Bump version to ${{ steps.get_version.outputs.version }}"
          git tag v${{ steps.get_version.outputs.version }}
          git push
          git push --tags

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
